export const SharedConfig = {
    RESPAWN_TIME: 180000,
    MAX_BLIP_STREAM_DISTANCE: 650,
    FORCE_SCREEN_SHAKE: true,
    FOOD_FATIGUE: 10,
    WATER_FATIGUE: 8,
    MOOD_FATIGUE: 20,
    MAX_PICKUP_RANGE: 2,
    INTERACTION_ALWAYS_ON: false,
    MAX_INTERACTION_RANGE: 8,
    MAX_AUDIO_STREAM_DISTANCE: 50,
    FUEL_TIME: 30000,
    FUEL_PRICE: 1.49
};
