const DefaultLocales = {
    titles: ['Aussehen', 'Gesichtsstruktur', 'Haare', 'Details', 'Make-Up', 'Daten', 'Fertigstellung'],
    LABEL_NAME: 'Name',
    LABEL_BIRTHDAY: 'Geburtsdatum',
    LABEL_GENDER: 'Geschlecht',
    LABEL_DAY: 'Tag',
    LABEL_MONTH: 'Monat',
    LABEL_YEAR: 'Jahr',
    LABEL_PREV: 'Vorheriges',
    LABEL_NEXT: 'Nächstes',
    LABEL_SAVE: 'Speichern',
    LABEL_FIELD_REQUIRED: 'Dieses Feld wird benötigt',
    LABEL_CANNOT_EXCEED: 'kann nicht übersteigen',
    LABEL_CANNOT_BE_LESS: 'kann nicht kleiner sein',
    LABEL_CHARACTER: 'Satzzeichen',
    LABEL_NO_SPECIAL: 'Keine Sonderzeichen verwenden',
    LABEL_NAME_NOT_AVAILABLE: 'Name ist bereits vergeben',
    LABEL_CHARACTER_GENDER: 'Männlich, Weiblich, Diverse',
    LABEL_VERIFIED: 'Alle Daten wurden validiert',
    characterName: 'Wie soll ihr Charakter heißen?',
    characterBirth: 'Wann wurde ihr Charakter geboren?',
    characterGender: 'Als was identifiziert sich ihr Charakter?',
    appearanceComponent: {
        LABEL_FRAME: 'Geschlechtsmerkmal',
        DESC_FRAME: 'Wie soll ihr Charakter aussehen?',
        LABEL_MASCULINE: 'Männlich',
        LABEL_FEMININE: 'Weiblich',
        LABEL_PRESETS: 'Presets',
        DESC_PRESETS: 'Not feeling creative? Choose a preset.',
        LABEL_FATHER: 'Vater',
        DESC_FATHER: 'Wie sah der Vater aus?',
        LABEL_MOTHER: 'Mutter',
        DESC_MOTHER: 'Wie sah die Mutter aus?',
        LABEL_FACEBLEND: 'Gesichtsmischung',
        DESC_FACEBLEND: 'Mischen Sie die Gesichtsstruktur Ihrer Mutter und Ihres Vaters',
        LABEL_SKINBLEND: 'Hautmischung',
        DESC_SKINBLEND: 'Mischen Sie die Hautfarben Ihrer Mutter und Ihres Vaters',
        LABEL_EYECOLOUR: 'Augenfarbe',
        DESC_EYECOLOUR: 'Verwenden Sie diesen Schieberegler, um eine Augenfarbe auszuwählen.',
        LABEL_FACE: 'Gesicht',
        LABEL_SKIN: 'Haut'
    },
    hairComponent: {
        LABEL_HAIRSTYLE: 'Frisur',
        DESC_HAIRSTYLE: `Wählen Sie Ihre Frisur, Farbe und Besonderheiten`,
        LABEL_HAIRSTYLE_COLOUR: 'Frisurenfarbe',
        LABEL_HAIRSTYLE_HIGHLIGHTS: 'Frisur-Besonderheiten',
        LABEL_EYEBROWS: 'Augenbrauen',
        DESC_EYEBROWS: 'Wählen Sie Ihre Augenbrauenform und -farbe.',
        LABEL_EYEBROWS_COLOUR: 'Augenbrauenfarbe',
        LABEL_FACIAL_HAIR: 'Gesichtsbehaarung',
        DESC_FACIAL_HAIR: 'Wählen Sie Ihre Gesichtsbehaarung, Farbe, Deckkraft und Besonderheit',
        LABEL_OPACITY: 'Deckkraft',
        LABEL_FACIAL_HAIR_COLOUR: 'Gesichtshaarfarbe',
        masculine: [
            'Close Shave',
            'Buzzcut',
            'Faux Hawk',
            'Shaved Sides Slicked Back',
            'Raised Front Same Length',
            'Col De Sacs and Long Back',
            'Close Shave and Loose Mohawk',
            'Ponytail',
            'Corn Rows',
            'Slicked Back Curly Back',
            'Slicked Back',
            'Spiked',
            'Short Bowl Cut',
            'Messy Long Length',
            'Dreads',
            'Straight Long Length',
            'Curly Long',
            'Straight Long Partial Messy',
            'Side Part Front Short',
            'Slicked Back Short',
            'Side Part Front Long',
            'Razer Side Part Slick',
            'Mullet',
            'Nightvision',
            'Corn Rows',
            'Starfish Corn Rows',
            'Zig Zag Corn Rows',
            'Large Snakelike Corn Rows',
            'Small Snakelike Corn Rows',
            'Side Swirl Corn Rows',
            'Flat Top',
            'Front Crown Long Back',
            'Shaved Sided Slicked Back',
            'Side Parted Shaved Sides',
            'Mohawk',
            'Messy Long Back',
            'Center Parted Bob',
            'Buzz Cut',
            'Faux Hawk',
            'Shaved Sides Slicked Back',
            'Raised Front Same Length',
            'Col De Sacs and Long Back',
            'Close Shave and Loose Mohawk',
            'Ponytail',
            'Corn Rows',
            'Slicked Back Curly Back',
            'Slicked Back',
            'Spiked',
            'Short Bowl Cut',
            'Messy Long Length',
            'Dreads',
            'Straight Long Length',
            'Curly Long',
            'Straight Long Partial Messy',
            'Side Part Front Short',
            'Slicked Back Short',
            'Side Part Front Long',
            'Razer Side Part Slick',
            'Mullet',
            'Corn Rows',
            'Starfish Corn Rows',
            'Zig Zag Corn Rows',
            'Large Snakelike Corn Rows',
            'Small Snakelike Corn Rows',
            'Side Swirl Corn Rows',
            'Flat Top',
            'Front Crown Long Back',
            'Shaved Sided Slicked Back',
            'Side Parted Shaved Sides',
            'Mohawk',
            'Messy Long Back',
            'Center Parted Bob',
            'Shaved Sides Flat Top',
            'Shaved Sides Short Top',
            'Elvis'
        ],
        feminine: [
            'Close Shave',
            'Short Bob',
            'Bob',
            'Pigtails',
            'Ponytail',
            'Braided Mohawk',
            'Braids',
            'Bob',
            'Faux Hawk',
            'French Twist',
            'Long Bob',
            'Loose Tied Ponytail',
            'Pixie',
            'Side Parted Shaved Bangs',
            'Top Knot',
            'Wavy Long',
            'Messy Tied Bandana',
            'Messy Bun with Cropped Bangs',
            'Bob with Feathers',
            'Tight Bun Cropped Bangs',
            'Frizzy Curly Afro',
            'Messy Wavy Bangs',
            'Tight Top Bun Braided',
            'Mullet',
            'Night Vision',
            'Braided Corn Rows',
            'Center Part Braided Corn Rows',
            'Diamond Corn Rows',
            'Pigtails with Bangs',
            'Star Braided Corn Rows',
            'Vertical Shaved Corn Rows',
            'Loose Tied Ponytail',
            'Short Mullet',
            'Shaved Sides Slicked Back',
            'Side Parted Shaved Bangs',
            'Mohawk',
            'Tied Pigtails with Bandana',
            'The Karen',
            'Center Parted Bob',
            'Pixie',
            'Bob',
            'Pigtails',
            'Loose Tied Ponytail',
            'Braided Mohawk',
            'Braids',
            'Straight Bob',
            'Faux Hawk',
            'French Twist',
            'Long Bob',
            'Ponytail Bun',
            'Pixie',
            'Side Parted Shaved Bangs',
            'Top Knot',
            'Wavy Long',
            'Messy Tied Bandana',
            'Messy Top Knot with Bangs',
            'Bob with Feathers',
            'Tight Bun Cropped Bangs',
            'Frizzy Curly Afro',
            'Messy Wavy Bangs',
            'Tight Top Bun Braided',
            'Mullet',
            'Corn Rows',
            'Center Parted Corn Rows',
            'Diamond Corn Rows',
            'Pigtails',
            'Star Braided Corn Rows',
            'Vertical Shaved Corn Rows',
            'Loosely Tied Ponytail',
            'Short Mullet',
            'Shaved Sides Slicked Back',
            'Side Parted Shaved Bangs',
            'Mohawk',
            'Tied Pigtails with Bandana',
            'The Karen',
            'Pixie Bob',
            'Tight Pony Tail Bun',
            'Pixie Cut',
            'Elvis'
        ],
        facial: [
            'Stubble',
            'Balbo',
            'Circle Beard',
            'Goatee',
            'Chin',
            'Chin Fuzz',
            'Pencil Chin Strap',
            'Scruffy',
            'Musketeer',
            'Mustache',
            'Trimmed Beard',
            'Stubble Beard',
            'Thin Circle Beard',
            'Horseshoe',
            'Pencil and Chops',
            'Chin Strap',
            'Balbo and Sideburns',
            'Mutton Chops',
            'Scruffy Beard',
            'Curly',
            'Curly and Beard',
            'Handlebar',
            'Faustic',
            'Otto and Patch',
            'Otto and Beard',
            'Light Franz',
            'The Hampstead',
            'The Ambrose',
            'Lincoln Curtain',
            'Clean Shaven'
        ],
        eyebrows: [
            'Balanced',
            'Fashion',
            'Cleopatra',
            'Quizzical',
            'Femme',
            'Seductive',
            'Pinched',
            'Chola',
            'Triomphe',
            'Carefree',
            'Curvaceous',
            'Rodent',
            'Double Tram',
            'Thin',
            'Penciled',
            'Mother Plucker',
            'Straight and Narrow',
            'Natural',
            'Fuzzy',
            'Unkempt',
            'Caterpillar',
            'Regular',
            'Mediterranean',
            'Groomed',
            'Bushels',
            'Feathered',
            'Prickly',
            'Monobrow',
            'Winged',
            'Triple Tram',
            'Arched Tram',
            'Cutouts',
            'Fade Away',
            'Solo Tram',
            'None'
        ]
    },
    structureComponent: [
        'Nasenbreite',
        'Höhe der Nasenunterseite',
        'Länge der Nasenspitze',
        'Nasensteg Tiefe',
        'Höhe der Nasenspitze',
        'Nase gebrochen',
        'Brauenhöhe',
        'Brauentiefe',
        'Wangenknochenhöhe',
        'Wangenknochenbreite',
        'Wangentiefe',
        'Augengröße',
        'Lippendicke',
        'Kieferbreite',
        'Kieferform',
        'Kinnhöhe',
        'Kinntiefe',
        'Kinnbreite',
        'Kinneinzug',
        'Nackenbreite'
    ],
    makeupComponent: {
        LABEL_STYLE: 'Stil',
        LABEL_OPACITY: 'Deckkraft',
        LABEL_COLOUR1: 'Farbe 1',
        LABEL_COLOUR2: 'Farbe 2',
        ids: {
            4: {
                name: 'Make-Up',
                description: 'Verbessern oder verändern Sie Ihr Aussehen mit dieser Kosmetik',
                labels: [
                    'Smoky Black',
                    'Bronze',
                    'Soft Gray',
                    'Retro Glam',
                    'Natural Look',
                    'Cat Eyes',
                    'Chola',
                    'Vamp',
                    'Vinewood Glamour',
                    'Bubblegum',
                    'Aqua Dream',
                    'Pin up',
                    'Purple Passion',
                    'Smoky Cat Eye',
                    'Smoldering Ruby',
                    'Pop Princess',
                    'Kiss My Axe',
                    'Panda Pussy',
                    'The Bat',
                    'Skull in Scarlet',
                    'Serpentine',
                    'The Veldt',
                    'Unknown 1',
                    'Unknown 2',
                    'Unknown 3',
                    'Unknown 4',
                    'Tribal Lines',
                    'Tribal Swirls',
                    'Tribal Orange',
                    'Tribal Red',
                    'Trapped in A Box',
                    'Clowning',
                    'Guyliner',
                    'Unknown 5',
                    'Blood Tears',
                    'Heavy Metal',
                    'Sorrow',
                    'Prince of Darkness',
                    'Rocker',
                    'Goth',
                    'Punk',
                    'Devastated'
                ]
            },
            5: {
                name: 'Errötungen',
                description: 'Make-up, das auf Ihre Wangen geht',
                labels: ['Full', 'Angled', 'Round', 'Horizontal', 'High', 'Sweetheart', 'Eighties']
            },
            8: {
                name: 'Lippenstift',
                description: 'Farbkosmetik zum auftragen auf die Lippen',
                labels: ['Color Matte', 'Color Gloss', 'Lined Matte', 'Lined Gloss', 'Heavy Lined Matte', 'Heavy Lined Gloss', 'Lined Nude Matte', 'Liner Nude Gloss', 'Smudged', 'Geisha']
            }
        }
    },
    overlaysComponent: {
        LABEL_STYLE: 'Stil',
        LABEL_OPACITY: 'Deckkraft',
        ids: {
            0: {
                name: 'Makel',
                description: 'Haben Sie irgendwelche Unvollkommenheiten?',
                labels: [
                    'Measles',
                    'Pimples',
                    'Spots',
                    'Break Out',
                    'Blackheads',
                    'Build Up',
                    'Pustules',
                    'Zits',
                    'Full Acne',
                    'Acne',
                    'Cheek Rash',
                    'Face Rash',
                    'Picker',
                    'Puberty',
                    'Eyesore',
                    'Chin Rash',
                    'Two Face',
                    'T Zone',
                    'Greasy',
                    'Marked',
                    'Acne Scarring',
                    'Full Acne Scarring',
                    'Cold Sores',
                    'Impetigo'
                ]
            },
            3: {
                name: 'Alterung',
                description: 'Wie alt sollte Ihr Charakter aussehen?',
                labels: [
                    "Crow's Feet",
                    'First Signs',
                    'Middle Aged',
                    'Worry Lines',
                    'Depression',
                    'Distinguished',
                    'Aged',
                    'Weathered',
                    'Wrinkled',
                    'Sagging',
                    'Tough Life',
                    'Vintage',
                    'Retired',
                    'Junkie',
                    'Geriatric'
                ]
            },
            6: {
                name: 'Teint',
                description: 'Wie wäre es mit etwas Akne, Hautausschlägen, etc ?',
                labels: ['Rosy Cheeks', 'Stubble Rash', 'Hot Flush', 'Sunburn', 'Bruised', 'Alchoholic', 'Patchy', 'Totem', 'Blood Vessels', 'Damaged', 'Pale', 'Ghostly']
            },
            7: {
                name: 'Sonnenbrand',
                description: 'Trockene Haut und Falten',
                labels: ['Uneven', 'Sandpaper', 'Patchy', 'Rough', 'Leathery', 'Textured', 'Coarse', 'Rugged', 'Creased', 'Cracked', 'Gritty']
            },
            9: {
                name: 'Sommersprossen',
                description: 'Muttermale und Dinge für Ihr Gesicht',
                labels: [
                    'Cherub',
                    'All Over',
                    'Irregular',
                    'Dot Dash',
                    'Over the Bridge',
                    'Baby Doll',
                    'Pixie',
                    'Sun Kissed',
                    'Beauty Marks',
                    'Line Up',
                    'Modelesque',
                    'Occasional',
                    'Speckled',
                    'Rain Drops',
                    'Double Dip',
                    'One Sided',
                    'Pairs',
                    'Growth'
                ]
            },
            11: {
                name: 'Körperfehler',
                description: 'Haben Sie irgendwelche Körperunvollkommenheiten?',
                labels: null
            }
        }
    },
    faces: [
        'Benjamin',
        'Daniel',
        'Joshua',
        'Noah',
        'Andrew',
        'Joan',
        'Alex',
        'Isaac',
        'Evan',
        'Ethan',
        'Vincent',
        'Angel',
        'Diego',
        'Adrian',
        'Gabriel',
        'Michael',
        'Santiago',
        'Kevin',
        'Louis',
        'Samuel',
        'Anthony',
        'Hannah',
        'Audrey',
        'Jasmine',
        'Giselle',
        'Amelia',
        'Isabella',
        'Zoe',
        'Ava',
        'Camilla',
        'Violet',
        'Sophia',
        'Eveline',
        'Nicole',
        'Ashley',
        'Grace',
        'Brianna',
        'Natalie',
        'Olivia',
        'Elizabeth',
        'Charlotte',
        'Emma',
        'Claude',
        'Niko',
        'John',
        'Misty'
    ],
    color: {
        hair: [
            'Black',
            'Dark Gray',
            'Medium Gray',
            'Darkest Brown',
            'Dark Brown',
            'Brown',
            'Light Brown',
            'Lighter Brown',
            'Lightest Brown',
            'Faded Brown',
            'Faded Blonde',
            'Lightest Blonde',
            'Lighter Blonde',
            'Light Blonde',
            'White Blonde',
            'Grayish Brown',
            'Redish Brown',
            'Red Brown',
            'Dark Red',
            'Red',
            'Very Red',
            'Vibrant Red',
            'Orangeish Red',
            'Faded Red',
            'Faded Orange',
            'Gray',
            'Light Gray',
            'Lighter Gray',
            'Lightest Gray',
            'Dark Purple',
            'Purple',
            'Light Purple',
            'Violet',
            'Vibrant Violet',
            'Candy Pink',
            'Light Pink',
            'Cyan',
            'Blue',
            'Dark Blue',
            'Green',
            'Emerald',
            'Oil Slick',
            'Shiney Green',
            'Vibrant Green',
            'Green',
            'Bleach Blonde',
            'Golden Blonde',
            'Orange Blonde',
            'Orange',
            'Vibrant Orange',
            'Shiny Orange',
            'Dark Orange',
            'Red',
            'Dark Red',
            'Very Dark Red',
            'Black',
            'Black',
            'Black',
            'Black',
            'Black'
        ],
        overlays: [
            'Red',
            'Pink',
            'Light Pink',
            'Lighter Pink',
            'Lightest Pink',
            'Light Maroon',
            'Maroon',
            'Light Brown',
            'Lighter Brown',
            'Lightest Brown',
            'White Pink',
            'Beige',
            'Brown Red',
            'Orange',
            'Orange Pink',
            'Lightest Pink',
            'Lighter Pink',
            'Pink',
            'Vibrant Pink',
            'Dark Pink',
            'Darker Pink',
            'Darkest Pink',
            'Red',
            'Lighter Red',
            'Vibrant Red',
            'Red Pink',
            'Purple',
            'Light Purple',
            'Dark Purple',
            'Darker Purple',
            'Darkest Purple',
            'Vibrant Purple',
            'Black Purple',
            'Blue',
            'Light Blue',
            'Lighter Blue',
            'Lightest Blue',
            'Cyan',
            'Sea Green',
            'Deep Sea Green',
            'Green',
            'Dark Green',
            'Light Green',
            'Yellow Green',
            'Dark Yellow',
            'Yellow',
            'Yellow Orange',
            'Dark Yellow Orange',
            'Vigrant Orange',
            'Dark Orange',
            'Blonde',
            'Blonde White',
            'White',
            'Gray',
            'Dark Gray',
            'Darkest Gray',
            'Black',
            'Light Blue',
            'Dark Blue',
            'Darkest Blue',
            'Light Brown',
            'Brown',
            'Dark Brown',
            'Darker Brown'
        ],
        eyes: [
            'Green',
            'Emerald',
            'Light Blue',
            'Ocean Blue',
            'Light Brown',
            'Dark Brown',
            'Hazel',
            'Dark Gray',
            'Light Gray',
            'Pink',
            'Yellow',
            'Purple',
            'Blackout',
            'Shades of Gray',
            'Tequila Sunrise',
            'Atomic',
            'Warp',
            'ECola',
            'Space Ranger',
            'Ying Yang',
            'Bullseye',
            'Lizard',
            'Dragon',
            'Extra Terrestrial',
            'Goat',
            'Smiley',
            'Possessed',
            'Demon',
            'Infected',
            'Alien',
            'Undead',
            'Zombie'
        ]
    }
};
