import * as alt from 'alt-server';
declare function economy(player: alt.Player): void;
declare function design(player: alt.Player): void;
declare function inventory(player: alt.Player): void;
declare function syncedMeta(player: alt.Player): void;
declare function time(player: alt.Player): void;
declare function weather(player: alt.Player): void;
declare function playTime(player: alt.Player): void;
declare function food(player: alt.Player): void;
declare function water(player: alt.Player): void;
declare function mood(player: alt.Player): void;
declare function vehicles(player: alt.Player): void;
declare const _default: {
    design: typeof design;
    economy: typeof economy;
    inventory: typeof inventory;
    playTime: typeof playTime;
    syncedMeta: typeof syncedMeta;
    time: typeof time;
    vehicles: typeof vehicles;
    food: typeof food;
    water: typeof water;
    mood: typeof mood;
    weather: typeof weather;
};
export default _default;
