export const SHARED_CONFIG = {
    RESPAWN_TIME: 25000,
    MAX_BLIP_STREAM_DISTANCE: 650,
    FORCE_SCREEN_SHAKE: true,
    FOOD_FATIGUE: 10,
    WATER_FATIGUE: 8,
    MAX_PICKUP_RANGE: 2,
    INTERACTION_ALWAYS_ON: false,
    MAX_INTERACTION_RANGE: 8,
    MAX_AUDIO_STREAM_DISTANCE: 50,
    VOICE_ON: false,
    FUEL_TIME: 15000,
    FUEL_PRICE: 2
};
